services:
  db:
    image: postgres:14
    env_file: ./backend/.env
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data

  migration:
    build: ./backend 
    env_file: ./backend/.env
    command: #
        bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    volumes:
        - ./backend/.:/code
    depends_on:
        - db

  api_django:
    build: ./backend  
    env_file: ./backend/.env
    command:
        bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
        - ./backend/.:/code
    stdin_open: true 
    tty: true 
    ports: 
        - 8000:8000

    depends_on: 
        - db
        - migration

  frontend:
    build: ./frontend
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
      
volumes:
    pgdata:
      